name: descubri
description: A reimagined way of searching for the best restaurants around your area. Made for those who wish to find the best meals.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.2
  firebase_analytics: ^7.1.1
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.3
  cupertino_icons: ^1.0.0
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"


flutter:
  uses-material-design: true

